# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mix_master}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Taylor"]
  s.date = %q{2009-09-05}
  s.description = %q{Allows modules to be unmixed at runtime from classes, much as Mixology or Mixico do.  Implemented in pure ruby with no C extensions.}
  s.email = %q{scott@railsnewbie.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "BUGS.rdoc",
     "GPL_LICENSE",
     "MIT_LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mix_master.rb",
     "lib/mix_master/mixer.rb",
     "lib/mix_master/mixin_table.rb",
     "lib/mix_master/module_extension.rb",
     "lib/mix_master/version.rb",
     "mix_master.gemspec",
     "rake_tasks/flog.rake",
     "rake_tasks/gems.rake",
     "rake_tasks/rdoc.rake",
     "rake_tasks/rspec.rake",
     "rake_tasks/sloc.rake",
     "rake_tasks/tags.rake",
     "spec/installation_spec.rb",
     "spec/mix_master_spec.rb",
     "spec/module_methods_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/version_spec.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/smtlaissezfaire/mix_master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Mix and unmix modules}
  s.test_files = [
    "spec/installation_spec.rb",
     "spec/mix_master_spec.rb",
     "spec/module_methods_spec.rb",
     "spec/spec_helper.rb",
     "spec/version_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<smtlaissezfaire-using>, [">= 0.1.5"])
    else
      s.add_dependency(%q<smtlaissezfaire-using>, [">= 0.1.5"])
    end
  else
    s.add_dependency(%q<smtlaissezfaire-using>, [">= 0.1.5"])
  end
end
